### ISSUE TITLE
ftt2024-12-15 19:32:39 4 [Warning] Access denied for user 'db'@'172.31.0.4' (using password: YES)

### ISSUE THREAD

**Issue by SuperDarius-git** [biblioverse/biblioteca#251]
Hi 

Please help me, as I am struggling with the installation. I left the database details as "db" (all of them) and also didn't touch the DATABASE_URL variable. I followed all instructions to the best of my knowledge, but I get an error when I run the first command for setting up the database. 

`docker compose exec biblioteca bin/console doctrine:migration:migrate --no-interaction`

The following is the error:

```
CRITICAL  [console] Error thrown while running command "'doctrine:migration:migrate' --no-interaction". Message: "An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'db'@'172.31.0.4' (using password: YES)" ["exception" => Doctrine\DBAL\Exception\ConnectionException^ { …},"command" => "'doctrine:migration:migrate' --no-interaction","message" => "An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'db'@'172.31.0.4' (using password: YES)"]

In ExceptionConverter.php line 101:
                                                                                                                              
  An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'db'@'172.31.0.4' (using password: YES)  
                                                                                                                              

In Exception.php line 28:
                                                                                         
  SQLSTATE[HY000] [1045] Access denied for user 'db'@'172.31.0.4' (using password: YES)  
                                                                                         

In Driver.php line 33:
                                                                                         
  SQLSTATE[HY000] [1045] Access denied for user 'db'@'172.31.0.4' (using password: YES)  
                                                                                         

doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--no-all-or-nothing] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] [<version>]
```

Please help me
Thank you
Darius

**Comment by SergioMendolia** [comment]
Hey! 

Sorry to hear that. Could you try this command first?

docker compose exec biblioteca bin/console doctrine:database:create 

If it fails please provide the error message and if it succeeds you can continue with the initial command. 

If any of these fail: could you show me your docker compose file and your .env.local file (remove any other secrets before)?

**Comment by SuperDarius-git** [comment]
Thank you so much for the reply. Here is the error after sending that command: 
```
Could not create database `db` for connection named default
An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'db'@'172.31.0.4' (using password: YES)
```

Here is my docker-compose.yml:
```

services:
  biblioteca:
    image: ghcr.io/biblioverse/biblioteca:latest
    command: ["/bin/sh", "-c" , "apache2-foreground" ]
    ports:
      - 4455
    depends_on:
      - db
    stdin_open: true
    tty: true
    volumes:
      - ./covers:/var/www/html/public/covers
      - ./books:/var/www/html/public/books
      - ./img:/var/www/html/public/media
      - .env:/var/www/html/.env
  db:
    image: mariadb:10.10
    environment:
      - MYSQL_ROOT_PASSWORD=db
      - MYSQL_DATABASE=db
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
    volumes:
      - mariadb:/var/lib/mysql

  typesense:
    image: typesense/typesense:27.1
    restart: on-failure
    ports:
      - 8983
      - 8108
    volumes:
      - searchdata:/data
    command: '--data-dir /data --api-key=################################### --enable-cors'

volumes:
    mariadb:
    searchdata:

```

My .env file: 

```
APP_SECRET=#######################################
DATABASE_URL="mysql://db:db@db:3306/db?serverVersion=mariadb-10.3.39&charset=utf8"
TYPESENSE_KEY=#################################################
```

Thanks again for your help.
Darius
